<?php
/**
  @file
  @brief Defines the Statsheet API functions.
  @note
    The following Data structures are used
    throughout this module.

    1. Statsheet Data Arrays.
       Statsheet Data Arrays are used to abstractly
       describe statsheets. This array structure
       extends the Table Data Array structure
       defined by simple_table, by adding several
       new parameters.

         array (
           'module'  => '<module name>'                         // Required if you are using any callback functions. This is used to load the module's include file.
           'caption' => <caption>                               // required.
           'rows' => array (<row name>, ...),                   // optional.
           'columns' => array (                                 // optional.
             array (
               'column_name' => <column name>,                  // required.
               'weight'      => <weight>),                      // required.
             ...
           ),
           'sortable'    => <true|false>,                       // optional (default true). Whether or not users may change the sorting.
           'sort_column' => <column name>,                      // optional.
           'label_column_name' => <column name>,                // optional. The name of the column that holds row labels.
           'show_totals' => <true|false>,                       // optional (default false).
           'fields' => array (
              array ('column_name'   => <column name>,          // required.
                     'row_name'      => <row name>,             // required.
                     'stat'          => <stat node id>,         // optional. The stat whose value will be displayed in the field. Overrides the value field if given.
                     'value'         => <field value>,          // required. Overriden by the stat field if given.
                     'display_value' => <display field value>), // optional. Overriden by the stat field if given.
                ...
           ),
           'field_width'     => <field width>,                  // optional (default 5).
           'submit_function' => <form submit callback>,         // required.
           'access_function' => <callback (user) -> bool>,      // optional.
           'default_field_value_function'  => <callback (column_name, row_name) -> field_value> // optional.
           'default_field_value_arguments' => array (<additional argument>) // optional. Additional arguments to pass to the default value function.
*/

/**
  @brief Accepts a field value and wraps that
    value within a textfield form element so that
    it can be embeded into an editable table.
  @param $value (string) the field value.
  @param $field_width (int) the textfield width.
  @param $suffix (string) an optional suffix.
  @return (array) the form element.
*/
function statsheet_wrap_value ($value, $field_width = 5, $suffix = null) {
  $elem = array (
    '#type'          => 'textfield',
    '#default_value' => $value,
    '#size'          => $field_width
  );
  if (!is_null ($suffix)) {
    $elem ['#suffix'] = $suffix;
  }
  return $elem;
}

/**
  @brief Defines the default field value function
    for editable tables. This function essentially
    wraps a call to the default field value
    function given in the data array and wraps the
    value returned within a textfield form element.
*/
function statsheet_wrap_default_value ($column_name, $row_name, $default_value_function, $default_value_arguments, $field_width) {
  $arguments = array_merge (
    array ($column_name, $row_name),
    $default_value_arguments
  );
  return statsheet_wrap_value (
    call_user_func_array ($default_value_function, $arguments),
    $field_width 
  );
}

/**
  @brief Accepts a Statsheet Data Array and returns
    a statsheet form array.
  @param $data (array) the Statsheet Data array.
  @return (array) the form.
*/
function statsheet_form ($form, $form_state, $data = null) {
  module_load_include ('inc', 'stat');

  if (is_null ($data)) {
    return array ();
  }

  if (isset ($data ['module'])) {
    module_load_include ('inc', $data ['module']);
  }

  // I. Wrap the field values within textfields if editable.
  global $user;
  $editable = isset ($data ['access_function']) && call_user_func ($data ['access_function'], $user);
  if ($editable) {
    $data ['sortable'] = false;

    // I.A. wrap field values.
    $field_width = isset ($data ['field_width']) ? $data ['field_width'] : 5;

    foreach ($data ['fields'] as &$field) {
      if (isset ($field ['stat'])) {
        $stat = node_load ($field ['stat']);
        if ($stat) {
          $field ['field_id'] = 'stat_' . $stat->nid;
          $field ['value'] = stat_get_value ($stat);
          $field ['display_value'] = statsheet_wrap_value (
            $field ['value'],
            $field_width,
            stat_get_unit ($stat)
          );
        }
      } else {
        if (!isset ($field ['display_value'])) {
          $field ['display_value'] = $field ['value'];
        }
      }
    }

    // I.B. wrap the default field value function.
    if (isset ($data ['default_field_value_function'])) {
      $data ['default_field_value_arguments'] = array (
        $data ['default_field_value_function'],
        $data ['default_field_value_arguments'],
        $field_width
      );
      $data ['default_field_value_function']  = 'statsheet_wrap_default_value';
    }
  }

  // II. get the table form.
  $form = drupal_get_form ('simple_table_form', $data);

  watchdog (
    'statsheet',
    '[statsheet_form] form: <pre>@form</pre>',
    array (
      '@form' => print_r ($form, true)
  ));

  // III. add the submit button if editable.
  if ($editable) {
    $form [] = array (
      '#type'   => 'submit',
      '#value'  => t ('Update'),
      '#submit' => array ('statsheet_form_submit')
    );
  }

  return $form;
}

/**
  @brief Implements hook_form_submit ().
  @details
    Updates any stats that were modified or created
    using the statsheet interface.
*/
function statsheet_form_submit ($form, $form_state) {
  module_load_include ('inc', 'stat');
  watchdog (
    'statsheet',
    '[statsheet_form_submit] form state: <pre>@form_state</pre>',
    array (
      '@form_state' => print_r ($form_state, true)
  ));
  foreach ($form_state ['input'] as $key => $value) {
    if (strpos ($key, 'stat_') !== 0) { continue; }
    $stat_nid = substr ($key, 5);
    watchdog (
      'statsheet',
      '[statsheet_form_submit] checking stat @stat_nid',
      array (
        '@stat_nid' => is_null ($stat_nid) ? '' : $stat_nid
    ));
    $stat = node_load ($stat_nid);
    if (!$stat) { continue; } 
    $stat_value = stat_get_value ($stat);
    watchdog (
      'statsheet',
      '[statsheet_form_submit] stat value: @stat_value value: @value same?: @same stat @stat',
      array (
        '@stat_value' => $stat_value,
        '@value'      => $value,
        '@same'       => $stat_value == $value ? 'yes' : 'no',
        '@stat' => print_r ($stat, true)
    ));
    if ($stat_value == $value) { continue; }
    watchdog (
      'statsheet',
      '[statsheet_form_submit] updating stat @stat_nid',
      array (
        '@stat_nid' => $stat_nid
    ));
    $stat = stat_set_value ($stat, $value);
    node_save ($stat);
  }
}
