<?php
/**
  @file
  @brief Defines the table blocks.
*/

/**
  @brief Implements hook_block_info ().
  @details
    Declares the stat table blocks.
*/ 
function hockey_boss_table_block_info () {
  return array (
    'hockey_boss_table_pps' => array (
      'info' => t ('Displays the current player\'s performance stats.')
    ),
    'hockey_boss_table_pfs' => array (
      'info' => t ('Displays the current player\'s fitness stats.')
    ),
    'hockey_boss_table_pgs' => array (
      'info' => t ('Displays the current player\'s game stats.')
    ),
    'hockey_boss_table_tr' => array (
      'info' => t ('Displays the current team\'s roster.')
    ),
    'hockey_boss_table_tgs' => array (
      'info' => t ('Displays the current team\'s game stats.'),
    ),
    'hockey_boss_table_lt' => array (
      'info' => t ('Displays the current league\'s teams.')
    ),
    'hockey_boss_table_pc' => array (
      'info' => t ('Displays the player comparison table.')
  ));
}

/**
  @brief Implements hook_block_view ().
  @details
    Defines the table blocks.
*/
function hockey_boss_table_block_view ($delta = '') {
  module_load_include ('inc', 'hockey_boss');
  module_load_include ('inc', 'hockey_boss_table');

  switch ($delta) {
    case 'hockey_boss_table_pps':
      $player_node = node_load (arg (1));
      if ($player_node && $player_node->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        return array (
          'subject' => 'Performance Stats',
          'content' => drupal_get_form ('simple_table_get_form', new PPSTable ($player_node->nid, date ('Y')))
        );
      }
      break;
    case 'hockey_boss_table_pfs':
      $player_node = node_load (arg (1));
      if ($player_node && $player_node->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        return array (
          'subject' => 'Fitness Stats',
          'content' => drupal_get_form ('simple_table_get_form', new PFSTable ($player_node))
        );
      }
      break;
    case 'hockey_boss_table_pgs':
      $player_node = node_load (arg (1));
      if ($player_node && $player_node->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        return array (
          'subject' => 'Game Stats',
          'content' => drupal_get_form ('simple_table_get_form', new PGSTable ($player_node, date ('Y')))
        );
      }
      break;
    case 'hockey_boss_table_tr':
      $team_node = node_load (arg (1));
      if ($team_node && $team_node->type == hockey_boss_TEAM_PROFILE_TYPE) {
        return array (
          'subject' => 'Roster',
          'content' => drupal_get_form ('simple_table_get_form', new TRTable ($team_node, date ('Y')))
        );
      }
      break;
    case 'hockey_boss_table_tgs':
      $team_node = node_load (arg (1));
      if ($team_node && $team_node->type == hockey_boss_TEAM_PROFILE_TYPE) {
        return array (
          'subject' => 'Game Stats',
          'content' => drupal_get_form ('simple_table_get_form', new TGSTable ($team_node->nid, date ('Y')))
        );
      }
      break;
    case 'hockey_boss_table_lt':
      $league_node = node_load (arg (1));
      if ($league_node && $league_node->type == hockey_boss_LEAGUE_PROFILE_TYPE) {
        return array (
          'subject' => 'Teams',
          'content' => drupal_get_form ('simple_table_get_form', new LTTable ($league_node))
        );
      }
      break;
    case 'hockey_boss_table_pc':
      $player_x = node_load (arg (1));
      $player_y = node_load (arg (2));
      if ($player_x && $player_y && $player_x->type == hockey_boss_PLAYER_PROFILE_TYPE && $player_y->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        return array (
          'subject' => '',
          'content' => drupal_get_form ('simple_table_get_form', new PCTable (array ($player_x->nid, $player_y->nid)))
        );
      }
  }
}
