<?php
/**
  @file
  @brief Defines the table blocks.
*/

/**
  @brief Implements hook_block_info ().
  @details
    Declares the stat table blocks.
*/ 
function hockey_boss_table_block_info () {
  return array (
    'hockey_boss_table_pps' => array (
      'info' => t ('Displays the current player\'s performance stats.')
    ),
    'hockey_boss_table_pgs' => array (
      'info' => t ('Displays the current player\'s game stats.')
  ));
}

/**
  @brief Implements hook_block_view ().
  @details
    Defines the table blocks.
*/
function hockey_boss_table_block_view ($delta = '') {
  module_load_include ('inc', 'hockey_boss');
  module_load_include ('inc', 'hockey_boss_table');

  switch ($delta) {
    case 'hockey_boss_table_pps':
      $player = node_load (arg (1));
      if ($player && $player->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        return array (
          'subject' => '',
          'content' => drupal_get_form ('simple_table_get_form', new PPSTable ($player->nid))
        );
      }
    case 'hockey_boss_table_pgs':
      $player = node_load (arg (1));
      if ($player && $player->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        return array (
          'subject' => '',
          'content' => drupal_get_form ('simple_table_get_form', new PGSTable ($player))
        );
      }
  }
}
