enable:
	drush pm-enable -v stat simple_table hockey_boss hockey_boss_stat hockey_boss_table

disable:
	drush pm-disable hockey_boss_table
	drush pm-disable hockey_boss_stat
	drush pm-disable hockey_boss
	drush pm-disable simple_table
	drush pm-disable stat

uninstall:
	drush pm-uninstall hockey_boss_table
	drush pm-uninstall hockey_boss_stat
	drush pm-uninstall hockey_boss
	drush pm-uninstall simple_table
	drush pm-uninstall stat
