<?php
/**
  @file
  @brief Defines the stat table blocks.
*/

/**
  @brief Implements hook_block_info ().
  @details
    Declares the stat table blocks.
*/ 
function hockey_boss_stat_table_block_info () {
  return array (
    'hockey_boss_stat_table_pps_table' => array (
      'info' => t ('Displays the current player\'s performance stats.')
    )
  );
}

/**
  @brief Implements hook_block_view ().
  @details
    Defines the stat table blocks.
*/
function hockey_boss_stat_table_block_view ($delta = '') {
  module_load_include ('inc', 'hockey_boss');
  module_load_include ('inc', 'hockey_boss_stat_table');

  switch ($delta) {
    case 'hockey_boss_stat_table_pps_table':
      $player = node_load (arg (1));
      if ($player && $player->type == hockey_boss_PLAYER_PROFILE_TYPE) {
        $content = drupal_get_form ('edit_table_form', hockey_boss_stat_table_pps ($player));
        return array (
          'subject' => '',
          'content' => $content
        );
      }
  }
}
